// ArduBlock — Arduino block kernel: pin blocks, C++ codegen, serial bridge.
// Generated by the Counted Repo Factory (seeds/seeds.yaml). Deterministic by construction.
// Layout: docs/REPO_STANDARD.md — core logic in src/lib/, public API in src/index.ts.

import { seededRandom } from "./lib/rng";
import { PinBlocks, CppCodegen, SerialBridge } from "./lib/modules";

export const SPEC = "Arduino block kernel: pin blocks, C++ codegen, serial bridge.";
export const MODULES = [{ id: "PinBlocks", name: "ArduBlock :: PinBlocks" }, { id: "CppCodegen", name: "ArduBlock :: CppCodegen" }, { id: "SerialBridge", name: "ArduBlock :: SerialBridge" }];
export { seededRandom };
export class Registry {
  private items = new Map<string, string>();
  constructor(seed = 42) {
    const rng = seededRandom(seed);
    for (const mod of MODULES) {
      const n = 1 + Math.floor(rng() * 4);
      for (let i = 0; i < n; i++) {
        this.items.set(mod.id + "-" + i, mod.name);
      }
    }
  }
  count(): number { return this.items.size; }
  get(id: string): string | undefined { return this.items.get(id); }
  ids(): string[] { return [...this.items.keys()]; }
  lookup(name: string): string[] {
    return this.ids().filter((id) => this.items.get(id) === name);
  }
}
